### PR TITLE
Fix: Union related bugs

### LINKED ISSUE #8: Crash on GameplayTagContainer.Union(...)
Diving into the code I found why:

`m_Indices.Explicit` and `m_Indices.Implicit` are null on new TagContainers

GameplayTagContainer.cs:345
Image

Which in turn, will crash inside `OrderedListUnion`

GameplayTagContainer.cs:302
Image

I lack deeper understanding of the Indices struct to know exactly where to initialize this 😬 

I hope this is enough to track the problem 🤞 

EDIT:

Adding a simple `GameplayTagContainerIndices.Create(ref union.m_Indices);` fixes it, but it makes me wonder, why is not that called by default on the constructor for `GameplayTagContainer` ?
(Again, I lack deeper understanding to know where to initialize the indices)

EDIT 2:

It was exactly the same issue with Intersection!
https://github.com/BandoWare/GameplayTags/commit/e6e13f33564fe463e9adbbc9356bd9ec472a29ec

### LINKED ISSUE #9: Wrong logic in GameplayTagContainer.Union(...)
GameplayTagContainer.cs:336
Image

Uhm... the union is empty if **BOTH** are empty. Not if _either of them_ are empty.

### LINKED ISSUE #10: Wrong logic in GameplayTagContainer.Copy<T>(...) and GameplayTagContainerIndices.CopyTo(...)
GameplayTagContainer.cs:218
Image

`dest.m_Indices.CopyTo(src.Indices);` does this

Image

Keep in mind, that `other` is our **src**... effectively nuking our original thingy.

EDIT:
wait...
```
         other.Explicit.AddRange(other.Explicit);
         other.Implicit.AddRange(other.Implicit);
```

so... add myself to myself? 🙃

### PR DESCRIPTION
**Pull request by miltoncandelero**
Fixes #8 by initializing the `m_Indices`

Fixes #9 by fixing the comparison

Fixes #10 by fixing both the `Copy` and `CopyTo` methods

### CODE REVIEW

File: Runtime/GameplayTagContainer.cs [hunk 1]
```diff
@@ -48,8 +48,8 @@ internal readonly void Clear()
       internal readonly void CopyTo(in GameplayTagContainerIndices other)
       {
          other.Clear();
-         other.Explicit.AddRange(other.Explicit);
```
Comment (miltoncandelero) [inline Runtime/GameplayTagContainer.cs:51]: Fixes #10

File: Runtime/GameplayTagContainer.cs [hunk 2]
```diff
@@ -48,8 +48,8 @@ internal readonly void Clear()
...
-         other.Implicit.AddRange(other.Implicit);
+         other.Explicit.AddRange(this.Explicit);
+         other.Implicit.AddRange(this.Implicit);
```
Comment (miltoncandelero) [inline Runtime/GameplayTagContainer.cs:52]: Partially Fixes #10 (This is the CopyTo method)

File: Runtime/GameplayTagContainer.cs [hunk 3]
```diff
@@ -215,7 +215,7 @@ public static void Copy<T>(GameplayTagContainer dest, in T src) where T : IGamep
             return;
 
          GameplayTagContainerIndices.Create(ref dest.m_Indices);
-         dest.m_Indices.CopyTo(src.Indices);
+         src.Indices.CopyTo(dest.m_Indices);
```
Comment (miltoncandelero) [inline Runtime/GameplayTagContainer.cs:218]: Partially Fixes #10 (This is the Copy<T> method)

File: Runtime/GameplayTagContainer.cs [hunk 4]
```diff
@@ -332,8 +332,9 @@ static void OrderedListUnion(List<int> a, List<int> b, List<int> dst)
          }
 
          GameplayTagContainer union = new();
+         GameplayTagContainerIndices.Create(ref union.m_Indices);
```
Comment (miltoncandelero) [inline Runtime/GameplayTagContainer.cs:335]: Fixes #8

File: Runtime/GameplayTagContainer.cs [hunk 5]
```diff
@@ -332,8 +332,9 @@ static void OrderedListUnion(List<int> a, List<int> b, List<int> dst)
...
 
-         if (lhs.IsEmpty || rhs.IsEmpty)
+         if (lhs.IsEmpty && rhs.IsEmpty)
```
Comment (miltoncandelero) [inline Runtime/GameplayTagContainer.cs:337]: Fixes #9

**Comment by felipemcoliveira** [comment]
@miltoncandelero appreciate the help!
